### ISSUE TITLE
The project should follow best practices

### ISSUE THREAD

**Issue by srv-twry** [TEDxHQ/TEDxHQ_TEMPLATE#4]
Following guidelines must be followed

- [ ]  The project should have a ```development``` branch and should contain the updated unstable version of the project. All the PR's should go to ```development```.
- [ ]  The project should have an ```Issues``` template for creating new Issues.
- [ ]  The project should have a ```Pull request``` template for creating new Pull requests.
- [ ]  The project should have a ```CONTRIBUTING.md``` file.
- [ ]  Update the ```README.md``` file with future roadmaps , license and other stuff.
- [ ]  Create label's such as ```Parent issue```,```enhancement``` etc. (Please suggest more). It can only be done by maintainers.

Please use this thread as a parent issue and suggest points which i may have missed. Create child issues for each and fire the PR.

**Comment by luckyman20** [comment]
@srv-twry I appreciate your efforts but we can't do all this in this repo as this is going to be deleted after deployment. So just make the necessary changes. We will be opening some cool projects soon, so we can follow the best practices on them.

**Comment by srv-twry** [comment]
@luckyman20 Sure. I thought it will be our long term project. I'll close it then :)

**Comment by 0x48piraj** [comment]
@srv-twry It was a great issue.
Keep that spirit! :sparkles:

**Comment by 0x48piraj** [comment]
@srv-twry 

Can you help us in creating `best practices` in other repositories ?
